hw1
earakelianEPAM/Test_automation_course pull request #3
Opened 2022-12-09 15:03 UTC by earakelianEPAM

2022-12-11 19:18 UTC, obitkin requested changes
- Rename repo to NameSurname
- Unite 2 maven project into 1
- Remove useless .idea files from git
- Remove target dir from git
- Add checkstyle plugin
- Fix checkstyle errors
Also, tests are very simple. You haven't found any problem. It's not requirements but it's possible to make it better

2022-12-12 12:49 UTC, earakelianEPAM commented
Tests are running successfully with maven command now

2022-12-14 12:44 UTC, obitkin requested changes
- Sorry, but the project structure is wrong. Check how it should look like here: https://github.com/jenkins-docs/simple-java-maven-app
- You should add testng suite for all tests

2022-12-14 12:47 UTC, obitkin commented
Also, don't use github web for commit push. It's a very bad way to do the changes. For example instead of 1 commit for file deleting I see hundreds of them

2022-12-15 12:33 UTC, obitkin requested changes
- Remove FirtsMavenProject directory
- Remove .idea files
- Remove target files
- Fix check style errors

2022-12-18 16:13 UTC, obitkin requested changes

2022-12-18 16:13 UTC, obitkin commented on src/test/java/com/epam/tc/hw1/DivideTest.java
> +}
Add an empty line at the end of this file to fix check style error

2022-12-18 16:13 UTC, obitkin commented on pom.xml
> +    </properties>
When I try to run tests via `mvn clean test` command I don't see any code or test compilation, or tests run. 

Try to find and fix the reason of this (it's in this part of pom file)

2022-12-20 13:17 UTC, obitkin approved these changes
Approved

2022-12-20 13:42 UTC, merged